### ISSUE TITLE
Support for Influx

### ISSUE THREAD

**Issue by Anand0583** [micronaut-projects/micronaut-micrometer#10]
Hello,

Does Micronaut Micrometer support integration with InfluxDB?

Thanks,
Anand.

**Comment by chantrybjss** [comment]
I managed to get influx working just by including the meter registry. This is what I had. 

`@Factory
public class InfluxConfiguration {
    @Property(name = "metrics.influx")
    private Map<String, String> influxProperties;

    @Bean
    @Primary
    @Singleton
    MeterRegistry meterRegistry() {
        return new InfluxMeterRegistry(
            new InfluxConfig(){
                @Override
                public String get(final String key) {
                    return influxProperties.get(key);
                }
            },
            Clock.SYSTEM
        );
    }
}`

Anything you do not configure under metrics.influx will get the defaults as per the influx documentation.

**Comment by thiagolocatelli** [comment]
@graemerocher I can give it a try on this one since I already have a influxdb infra-structure at home so it would be easier to test. I can take a look once I am done with the vault config client.

**Comment by graemerocher** [comment]
@thiagolocatelli thanks would be a great help!

**Comment by thiagolocatelli** [comment]
@graemerocher ok, will work on it next week!

**Comment by thiagolocatelli** [comment]
@graemerocher already have the code for influx, elastic and datadog implemented locally. Should each of these go into separate pull requests?

**Comment by thiagolocatelli** [comment]
Pull Request sent.
