### ISSUE TITLE
Update Netty version once it's updated on core

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-micrometer#134]
Once micronaut-core is updated to Netty 4.1.52 (or another one), revert this change https://github.com/micronaut-projects/micronaut-micrometer/pull/133 and update version in this module.

**Comment by alvarosanchez** [comment]
Can we not remove the `nettyVersion` property from here and use the one from micronaut-core?

`micronaut-bom` imports `netty-bom`, which should resolve all `io.netty` dependencies.

**Comment by ilopmar** [comment]
Probably. I think the problem was that we were not able to upgrade Netty in core (because of some regressions they had in different versions) and we wanted to make sure we were using the same version here. If we don't pin the version here dependabot/dependency-upgrade will upgrade the version here. Then, in users' apps with micrometer the new netty version would be used, leading to issues.

**Comment by ilopmar** [comment]
Btw, at this moment it's safe to upgrade to the same one using in core (4.1.54 I believe)

**Comment by alvarosanchez** [comment]
Right. Dependabot will attempt to upgrade the version if you have one defined explicitly. If you omit it and let it be resolved from the BOM, it should do nothing.

Will try that approach
