### ISSUE TITLE
Support Micrometer Datadog api approach

### ISSUE THREAD

**Issue by PandaXass** [micronaut-projects/micronaut-micrometer#15]
Hi,

Is it possible for Micronaut to support Micrometer Datadog api approach as https://micrometer.io/docs/registry/datadog#_direct_to_datadog_api_approach documented?

As I understand for now, Micronaut only integrates Micrometer using StatsD with Datadog flavor to ship the metrics when pushing the metrics to Datadog.

**Comment by graemerocher** [comment]
Addressed by https://github.com/micronaut-projects/micronaut-micrometer/pull/16
