### ISSUE TITLE
Bad content-type in response of /prometheus endpoint

### ISSUE THREAD

**Issue by STRRL** [micronaut-projects/micronaut-micrometer#17]
According to Prometheus [Exposition formats](https://prometheus.io/docs/instrumenting/exposition_formats/#text-based-format), `Content-Type` is expected to `text/plain; version=0.0.4`, but actual is `application/json`.

**Comment by graemerocher** [comment]
Seems https://github.com/micronaut-projects/micronaut-micrometer/blob/master/micrometer-registry-prometheus/src/main/java/io/micronaut/configuration/metrics/micrometer/prometheus/management/PrometheusEndpoint.java needs to declare it produces `text/plain` on the `@Read` method

**Comment by STRRL** [comment]
Should append `version=0.0.4`. Still in hidden trouble.
