### ISSUE TITLE
DatadogMeterRegistry isn't closed

### ISSUE THREAD

**Issue by tburch** [micronaut-projects/micronaut-micrometer#214]
I noticed this with the `DatadogMeterRegistry`, but it might apply to the `CompositeMeterRegistry`. The registry that is built by the factory doesn't have its `close` method hooked up, so if you have a short-lived (less than the `step` configuration) application that you want metrics for, they are not published.

A workaround is to manually close the `DatadogMeterRegistry` with something like this (in Kotlin):
```
try {
    val dd = applicationContext.findBean(DatadogMeterRegistry::class.java)
    if (dd.isPresent) {
        log.info { "Closing ${dd.get().javaClass.simpleName}" }
        dd.get().close()
        log.info { "Closed ${dd.get().javaClass.simpleName}" }
    }

} catch (e: Exception) {
    log.warn(e) { "Couldn't close the DatadogMeterRegistry!" }

}
```

### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a CLI application that publishes metrics to DataDog.
2. Run the application
3. Observe that metrics are not published to DataDog 

### Expected Behaviour

When the application context closes, the `close` in `DatadogMeterRegistry`is called. Alternatively, I believe the `close` method in `CompositeMeterRegistry` could just be annotated with `@PreDestroy`.

### Actual Behaviour

The application context closes without calling `close` on the `DatadogMeterRegistry` instance.

### Environment Information
- **Micronaut Version:** `2.2.1`
- **JDK Version:** `openjdk version "11.0.9.1" 2020-11-04`

**Comment by alvarosanchez** [comment]
I was planning to validate it myself. If you already did, and are in a position to send a PR, that would be great. Go ahead.

**Comment by tburch** [comment]
It looks like annotating `MeterRegistryFactory#compositeMeterRegistry` with `@Bean(preDestroy = "close")` should do the trick, but I'm struggling to write a test that verifies it. This is likely better than having to annotate all registry factories.

**Comment by alvarosanchez** [comment]
`CompositeMeterRegistry` has a `close` method, so I think it is the right thing to do even if there were no bugs.

Thanks for the contribution!
