### ISSUE TITLE
race condition when adding common tags to inbuilt metrics

### ISSUE THREAD

**Issue by meredrica** [micronaut-projects/micronaut-micrometer#243]
We have a common library (simple maven JAR) that gets added to every micronaut.
The library adds the pod name and the app name to each metric via common tags - so we can distinguish them.
We observed that sometimes the tags don't get added to every metric until the pod is restarted, so we are confident it's a race condition.
Specifically the ``process`` and ``system`` values seem to be affected - ``executor`` and -``http.server.requests`` seem fine.
We did not check every metric.

One Idea I still have (and could not verify yet) is that this has to do with the fact that we inject a config property.
However, this doesn't explain why we see the common tags on some metrics and not on others.

Here is some example code. You'll notice we tried quite a few things already
```java
@Context
@Primary
// used to be @Bean  and @Singleton - neither helped
// we also tried with a general purpose configurer - same story
public class MeterRegistryConfig implements MeterRegistryConfigurer<ElasticMeterRegistry> {

    @Property(name = "micronaut.application.name", defaultValue = "unknown-app-name")
    private String appName;

    @Override
    public void configure(ElasticMeterRegistry meterRegistry) {
        meterRegistry
                .config()
                .commonTags("pod.name", Optional.ofNullable(System.getenv("HOSTNAME")).orElse("unknown-host"), "app.name", appName);
    }

    @Override
    public Class<ElasticMeterRegistry> getType() {
        return ElasticMeterRegistry.class;
    }

    @Override
    public boolean supports(ElasticMeterRegistry meterRegistry) {
        return true;
    }
}

```

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Add elastic search monitoring
2. Add the registry config below
3. deploy to kubernetes etc and start/stop pods until the bug occurs

### Expected Behaviour
When adding a common tag to a meter registry it should appear on all metrics.

### Actual Behaviour
Common tags don't always appear on some metrics.
Specifically ``process.uptime`` and the likes are affected.
They are sometimes present, sometimes not and it's over the lifetime of a pod so I guess it's a race condition.

### Environment Information

- **Operating System**: OpenShift 3.11
- **Micronaut Version:** 2.4.1
- **JDK Version:** 15, also happens on others

**Comment by meredrica** [comment]
Here is an older incarnation of the configurer in case we broke something since then.
```
import io.micrometer.core.instrument.MeterRegistry;
import io.micronaut.configuration.metrics.aggregator.MeterRegistryConfigurer;
import io.micronaut.context.annotation.Property;
import io.micronaut.context.annotation.Value;

import java.util.Optional;

public class MeterRegistryConfig implements MeterRegistryConfigurer {

    @Property(name = "micronaut.application.name", defaultValue = "unknown-app-name")
    private String appName;

    @Override
    public void configure(MeterRegistry meterRegistry) {
        meterRegistry
                .config()
                .commonTags(
                        "pod.name", Optional.ofNullable(System.getenv("HOSTNAME")).orElse("unknown-host"))
                .commonTags("app.name", appName);
    }

    @Override
    public boolean supports(MeterRegistry meterRegistry) {
        return true;
    }
}
```

**Comment by JouperCoding** [comment]
Hello,

I see the same behavior when trying to disable some meters I don't wish to leverage. For example i may only want 2 jvm meters and 1 executor meter and then filter out the rest.

By creating a simple micronaut project 2.5.1 and including this
```
    //Micrometer
    compile "io.micronaut.micrometer:micronaut-micrometer-core"
    // micrometer-registry-statsd also pulls in micrometer-core so included above to verbose example
    compile "io.micronaut.micrometer:micronaut-micrometer-registry-statsd"
    // Also required to enable endpoint
    compile "io.micronaut:micronaut-management"
```

And then creating a registry configurer which denies which meters to register based on a white list as follows

```java
@Singleton
@RequiresMetrics
public class GlobalMeterRegistryConfigurer implements MeterRegistryConfigurer<MeterRegistry> {

	private static final Logger log = LoggerFactory.getLogger(GlobalMeterRegistryConfigurer.class);

	@Override
	public void configure(MeterRegistry meterRegistry) {

		meterRegistry.config().meterFilter(
			MeterFilter.denyUnless(id -> {
				String name = id.getName();
				try{
					return EMeters.valueOf(name).isEnabled();
				} catch (Exception ex){
					log.info("Unknown meter: {}", name);
					return false;
				}
			})
		);

	}

	@Override
	public Class<MeterRegistry> getType() {
		return MeterRegistry.class;
	}

}
```

This leads to inconsistent results for every application launch even on local dev setup.

**One of the following occurs for every application launch.**
1. The filter is not applied at all and all meters are available when checking the /metrics endpoint
2. Some of the meters are removed (usually executors meters) but not the jvm and system meters.
3. On very few occasions the desired meters are disabled and only the ones I'm interested in are active.

**Comment by graemerocher** [comment]
Seems like an ordering issue, have you tried implementing `Ordered` in your configurer and using highest priority?

**Comment by JouperCoding** [comment]
@graemerocher I'm assuming you mean using the @Order annotation, if so I just tested it with the following results.

1. @Order on class level prio -1 = all meters are removed
2. @Order on class level prio 99999 = all meter are removed
3. @Order on configure method prio -1 = only executor meters are removed
4. @Order on configure method prio 99999  = all meter are removed

Let me know if you need me to test something else or if I did it wrong :)

**Comment by JouperCoding** [comment]
Adding @Order seems to solve the common tag problem. Was able to verify that all my meters had the common tags now. As well as what the initial issue described. The process.uptime will get the common tag if you apply 

```java
@Order(Integer.MAX_VALUE)
@Singleton
@RequiresMetrics
public class GlobalMeterRegistryConfigurer implements MeterRegistryConfigurer<MeterRegistry>, Ordered {
```

@graemerocher Perhaps this should be mentioned in the Micronaut + Micrometer documentation?

**Comment by graemerocher** [comment]
Agreed, would you like to send a PR?

**Comment by JouperCoding** [comment]
@graemerocher Sure, I can write something up and create a PR for you!
