### ISSUE TITLE
Support Micrometer 1.7.0+ and InfluxDB 2.0 

### ISSUE THREAD

**Issue by ckosmowski** [micronaut-projects/micronaut-micrometer#263]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [-] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Try to use a micronaut project with an influxdb 2.0 Database

### Expected Behaviour

- New Configuration options for authentication are present (Auth token Header)
- Configuration options for buckets instead of databases are present
- Micronaut reports metrics to InfluxDB 2.0
- Micronaut uses micrometer 1.7.0+

### Actual Behaviour
- Configuration options are missing
- As the time of writing: Micronaut uses mirometer 1.6.6
- Connection with InfluxDB 2.0 fails

### Environment Information

- **Operating System**: Apline Linux
- **Micronaut Version:** 2.5.3
- **JDK Version:** AdoptOpenJdk15

**Comment by jameskleeh** [comment]
This was done with the 4.0.0 release
