### ISSUE TITLE
Adding a statsd registry prevents app from starting in 1.1.4

### ISSUE THREAD

**Issue by chochos** [micronaut-projects/micronaut-micrometer#27]
I have an app with a bunch of timers created using micrometer's `Metrics` static methods. When adding the statsd registry, the app won't start with 1.1.4, but works fine in 1.1.3.

The error:

```
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [meterRegistryProvider] of class: io.micronaut.configuration.metrics.binder.executor.ExecutorServiceMetricsBinder

Message: Multiple possible bean candidates found: [io.micrometer.statsd.StatsdMeterRegistry, io.micrometer.core.instrument.composite.CompositeMeterRegistry]
Path Taken: new ExecutorServiceMetricsBinder([Provider meterRegistryProvider])
```

Here's a simple example to reproduce the bug:

https://github.com/chochos/broken-micronaut-metrics

**Comment by graemerocher** [comment]
This was fixed a while back with https://github.com/micronaut-projects/micronaut-micrometer/commit/d7711c1c1feb7eac4146b0a104181355686d28fe
