### ISSUE TITLE
NOT RECEIVING ANY BUCKETS IN PROMETHEUS METRICS

### ISSUE THREAD

**Issue by Aditya010** [micronaut-projects/micronaut-micrometer#279]
### Feature description

I want to analyze P99-metrics for my Micronaut project but there is are no buckets for that as we are getting in Spring Framework. Is there any other way for that or am I missing something?

**Comment by ilopmar** [comment]
Please share a sample application that reproduces the problem.

**Comment by Aditya010** [comment]
Hey, There is no problem, Actually, I want to explore P99-metric via Micronaut and the metrics provided in micronaut via Prometheus registry are limited. If we receive buckets like that of Spring that would be great.
Ref: https://micronaut-projects.github.io/micronaut-micrometer/latest/guide/#metricsAndReportersPrometheus
Is there any way get such metrics?

**Comment by ilopmar** [comment]
Please ask usage questions in our Gitter channel: https://gitter.im/micronautfw
