### ISSUE TITLE
http metrics are reported as summary in prometheus, which is incompatible with distributed applications

### ISSUE THREAD

**Issue by eladidan** [micronaut-projects/micronaut-micrometer#288]
### Expected Behavior

`http.server[client].requests` metric should have meaningful percentiles in prometheus. 
Since latency is usually monitored in terms of percentiles and not averages, then a `summary` metric that calculates those quantiles on the client, is useless for a distributed application where you may want to calculate that value over in aggregate over different dimensions.

### Actual Behaviour

`http.server[client].requests` metric is collected as `summary` in `prometheus`, as per [micrometer docs](https://micrometer.io/docs/concepts#_timers)

### Steps To Reproduce

1. Run an http server with metrics enabled on port `8080`, and a prometheus endpoint on port `40385`
2. `curl localhost:8080`
3. Observe metrics via `curl localhost:40385/prometheus`

metrics will be of type `summary`

### Environment Information

Irrelevant

### Version

2.5.9

**Comment by eladidan** [comment]
Happy to open a PR for this if you support the change

**Comment by graemerocher** [comment]
PRs welcome of course

**Comment by eladidan** [comment]
happy to open it but would you support this change? Would you want it to be enabled by default or configurable via a setting?

**Comment by graemerocher** [comment]
it would need to be configurable in order to not break applications that prefer the existing behaviour

**Comment by umutkocasarac** [comment]
It is possible to add percentile to the HTTP server metrics like below. If you think adding this MeterFilter to the micronaut-micrometer project is valuable then I can create PR for it.

`@Factory
public class MeterFilterFactory {

    @Bean
    @Singleton
    MeterFilter createDistributionMeterFilter() {
        return new MeterFilter() {
            @Override
            public DistributionStatisticConfig configure(Meter.Id id, DistributionStatisticConfig config) {
                if (id.getName().startsWith(METRIC_HTTP_SERVER_REQUESTS)) {
                    return DistributionStatisticConfig.builder()
                        .percentiles(0.95, 0.99)
                        .build()
                        .merge(config);
                }
                return config;
            }
        };
    }
}`

**Comment by graemerocher** [comment]
PRs welcome
