### ISSUE TITLE
micrometer RxJava interceptors

### ISSUE THREAD

**Issue by rys-gw-wal** [micronaut-projects/micronaut-micrometer#337]
### Expected Behavior

@TimedInterceptor, @CountedInterceptor process  RXJava.Single as Reactive.Mono Object: Here is code from TimedInterceptor:

                            if (context.getReturnType().isSingleResult()) {
                                Mono<?> single = Publishers.convertPublisher(interceptResult, **Mono.class**);
                                result = single.doOnSubscribe(d -> reactiveInvokeSample.set(initSamples(timedAnnotations)))
                                        .doOnError(throwable -> finalizeSamples(timedAnnotations, throwable.getClass().getSimpleName(), reactiveInvokeSample.get()))
                                        .doOnSuccess(o -> finalizeSamples(timedAnnotations, "none", reactiveInvokeSample.get()));
                            } 

### Actual Behaviour

Exception is thrown: java.lang.ClassCastException: class io.reactivex.internal.operators.single.SingleToFlowable cannot be cast to class reactor.core.publisher.Mono (io.reactivex.internal.operators.single.SingleToFlowable and reactor.core.publisher.Mono are in unnamed module of loader 'app')

### Version

4.1.1

**Comment by graemerocher** [comment]
You need to add `micronaut-rxjava2` dependency to your classpath. See https://micronaut-projects.github.io/micronaut-rxjava2/latest/guide/

**Comment by rys-gw-wal** [comment]
there is dependency in  my my build.gradle file: 
**implementation("io.micronaut.rxjava2:micronaut-rxjava2")**

**Comment by rys-gw-wal** [comment]
there is dependency in my my build.gradle file:
implementation("io.micronaut.rxjava2:micronaut-rxjava2")
and 
Exception  java.lang.ClassCastException: class io.reactivex.internal.operators.single.SingleToFlowable cannot be cast to class reactor.core.publisher.Mono (io.reactivex.internal.operators.single.SingleToFlowable and reactor.core.publisher.Mono are in unnamed module of loader 'app') is still thrown

**Comment by graemerocher** [comment]
Can you provide an example with steps to reproduce?

**Comment by gerbil14** [comment]
Sorry for a late replay, an example application is attached
[5naut-5meter-rx.tar.gz](https://github.com/micronaut-projects/micronaut-micrometer/files/7906455/5naut-5meter-rx.tar.gz)

**Comment by rogerpereira123** [comment]
I am experiencing similar behavior with RxJava3 as well. Here is an example application 
Repo: https://github.com/rogerpereira123/micronaut-micrometer-rxjava3 
[App.ket](https://github.com/rogerpereira123/micronaut-micrometer-rxjava3/blob/main/app/src/main/kotlin/mn/micrometer/rxjava3/App.kt)
[Test](https://github.com/rogerpereira123/micronaut-micrometer-rxjava3/blob/main/app/src/test/kotlin/mn/micrometer/rxjava3/AppTest.kt)

Stack Trace:
```
class io.reactivex.rxjava3.internal.operators.single.SingleToFlowable cannot be cast to class reactor.core.publisher.Mono (io.reactivex.rxjava3.internal.operators.single.SingleToFlowable and reactor.core.publisher.Mono are in unnamed module of loader 'app')
java.lang.ClassCastException: class io.reactivex.rxjava3.internal.operators.single.SingleToFlowable cannot be cast to class reactor.core.publisher.Mono (io.reactivex.rxjava3.internal.operators.single.SingleToFlowable and reactor.core.publisher.Mono are in unnamed module of loader 'app')
	at io.micronaut.configuration.metrics.micrometer.intercept.TimedInterceptor.intercept(TimedInterceptor.java:102)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
```

Removing `@Timed` resolves the error. It appears that the  [timed interceptor](https://github.com/micronaut-projects/micronaut-micrometer/blob/master/micrometer-core/src/main/java/io/micronaut/configuration/metrics/micrometer/intercept/TimedInterceptor.java#L102) tries to convert Rx types to Reactor types and fails.  I tried to think about best way to fix this but couldn't think about an easier way other than having to use something like [reactor-addons](https://github.com/reactor/reactor-addons) 🤔

**Comment by graemerocher** [comment]
@n0tl3ss another one for you to take a look at related to the previous problem
