### ISSUE TITLE
Runaway HTTP-Metrics due to use of unsafe user-input or crafted URIs as metric labels

### ISSUE THREAD

**Issue by Robin479** [micronaut-projects/micronaut-micrometer#397]
### Expected Behavior

When running a Micronaut application with CORS and Micrometer metrics enabled, the user-input URI (especially during CORS preflights) is **NOT** used as the fallback for the "uri" label of the `http.server.request` metric in cases where the target endpoint and its URI-template cannot be determined.

In general, the incoming URI should never be used as the `uri` label on the `http.server.request` metric, because it entails insecure user input. The label on the metric should remain empty or should be set to a fixed value, if the target endpoint and its URI-template cannot be determined. The URI may contain payload such as encoded IDs which potentially lead to a huge number of distinct values for the `uri` label on this metric, which doesn't scale in downstream components related to monitoring, e.g. the Prometheus scraping endpoint's payload grows over time, which slows down your Prometheus instance.

A similar thing applies to HTTP Client metrics, where a manually constructed URI (or the URI given by the user in a forwarding-proxy) should not be used as a metric label, because it grows the number of distinct values for that label, if the path is crafted manually and/or has parameters encoded into it.

### Actual Behaviour

In case of a CORS preflight, the URI from the request (including payload such as IDs) is used for the "uri" label of the `http.server.requests` metric, which leads to an ever-growing list of distinct values for this label.
This can be seen by calling the Prometheus scraping endpoint after such requests have occurred. This growing behavior doesn't scale.

In case of any random HttpClient request to any URI, the URI path is used as the "uri" label of the `http.client.requests` metric, which leads to an ever-growing list of distinct values for this label, if the path is manually crafted and/or has parameter values encoded into it.
This can be seen by calling the Prometheus scraping endpoint after such requests have occurred. This growing behavior doesn't scale.

In case of any random HttpClient request to any URI, the "Host" header of the request is used as the "host" label of the `http.client.requests` metric, which leads to an ever-growing list of distinct values for this label, in case this header payload is crafted manually or provided via an incoming request in a forwarding-proxy (in which case it's our own domain).
This can be seen by calling the Prometheus scraping endpoint after such requests have occurred. This growing behavior doesn't scale.

### Steps To Reproduce

Run these tests: https://github.com/Robin479/micronaut-bugs/tree/main/http-metrics/src/test/java/de/ooch/micronaut/bugs

### Example Application

https://github.com/Robin479/micronaut-bugs/tree/main/http-metrics/src/test/java/de/ooch/micronaut/bugs

### Version

3.4.3

**Comment by graemerocher** [comment]
@n0tl3ss one for you to take a look at

**Comment by n0tl3ss** [comment]
HI @Robin479 As you saw there were some changes. If you want to test it by yourself you need to clone `micronaut-core` and then you can build it by running the ` ./gradlew publishToMavenLocal` after that you can use the SNAPSHOT version locally. About the CORS preflights I am not sure should we return 404 when the route doesn't exists, now it returns the status 200. Because we can't match to any route inside the router we put the whole path inside the metrics and I think that is good approach because you can have a track in which way users are trying to use missing routes when they are using the web application. About the last one I am not sure what you expect with the client metrics. We were thinking about introducing UriTemplate inside the raw HTTP client so request can be parametrised and metrics should display them well but when using the old raw one it will still have the whole path. If I correctly understand you, You want that in that case instead of the path of the http request the value of the Host header should appear? 

I tried your new test `testUnmatchedRequestsDontProduceRunawayServerMetrics` and it is failing because of described issue above. If we fix the `CorsFilter` to return only 200 for existing routes then I think your test will pass. 😄

**Comment by Robin479** [comment]
@n0tl3ss The number of distinct values for the "uri" label on the two metrics in question (as well as the "host" label on the client metric in certain scenarios) can grow uncontrollably, because they effectively entail dynamic input. This doesn't scale. This is at least a memory leak and a security issue, because these label values – once initialized – will stay present in the Prometheus scraping endpoint for the remainder of the JVM's life, unless explicitly reset, even if the actual count for each individual URI value never changes, which slowly degrades the performance of your monitoring infrastructure as the number of distinct values grows.
Also, if the user input entails personal information such as account-IDs or similar, this information would show up on screens of monitoring operators, that are not supposed to see this stuff.

You should simply never use dynamic data for metric labels – especially no user-input.

I can see, how it might be interesting to know, what "unmatched" paths the users of my API might haven taken, so I can "fix" clients where I'm in control of the source code, but this is more of a debug-level information, because I cannot fix every client, and malicious client may even overload my monitoring infrastructure. The untemplated / raw URI should simply not be tracked by default, especially, if these unmatched paths encode IDs or personal information. That's why I'm saying the fallback calls to "Request.getUri()" and "Request.getHeaders().get("Host")" in the metric filters should be replaced with static content such as "UNMATCHED" (similar to the static "NOT_FOUND", which is substituted in the "WebMetricsPublisher" for the URI on regular 404 requests).

Regarding the "host" label on the client metric: Currently, this label is set to the value of the "Host" header of the outgoing request by default. If you implement a forwarding-proxy like documented [here](https://docs.micronaut.io/latest/guide/#proxyClient) (which implicitly makes **everything** a user-input) or if you have any other reason to set this header dynamically for some reason, then again: the number of distinct values for the metric label can grow uncontrollably and information might be disclosed to monitoring operators, that are not supposed to see this stuff.

**Comment by graemerocher** [comment]
hi @Robin479 I can understand your perspective, I guess our caution here is around breaking existing applications. What Micronaut is doing is not terribly different to what other frameworks do. For example Spring uses https://github.com/spring-projects/spring-boot/blob/68bd9d6b6d38631d1d748c087e522439e9e867f0/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics/web/servlet/WebMvcTags.java#L158 which includes the URI in the computation of the tags.

So they are also using user input as metric tags. In terms of workarounds you have the option to disable the web metrics with in your configuration:

```yaml
micronaut.metrics.binders.web.enabled: false
```

If they don't work for your use case. Beyond that what do you propose as a solution that could resolve this issue? Another setting to disable the host and URI? 

In the case of the raw HTTP client there is no route to associate so everything would always be `UNMATCHED`.

I can see cases where the host header is useful if you are not using a forwarding proxy, so we can't just change this, would a setting to enable or disable this suffice?

Open to suggestions here

**Comment by olvesh** [comment]
@graemerocher - what you say is wrong and not what is happening in Spring Boot. You link to the `getPathInfo` method in SpringBoot, but if you take a look at 
https://github.com/spring-projects/spring-boot/blob/68bd9d6b6d38631d1d748c087e522439e9e867f0/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics/web/servlet/WebMvcTags.java#L110
you will see that the `getPathInfo(request)` is only used to send `URI_ROOT` or `URI_UNKNOWN`  

The calling method `public static Tag uri(...)` first tries to find a match using the `getMatchingPattern(request)`

This issue IMO makes Micronaut unusable & unsafe for observability purposes as it will potentially overload downstream metrics services with potentially infinite dimensions if a request misses the configured controllers. 

Workarounds are welcome :-)

**Comment by graemerocher** [comment]
It is fixed in 3.4.4 and above https://github.com/micronaut-projects/micronaut-core/pull/7354 to my knowledge

**Comment by n0tl3ss** [comment]
> It is fixed in 3.4.4 and above [micronaut-projects/micronaut-core#7354](https://github.com/micronaut-projects/micronaut-core/pull/7354) to my knowledge

In the end we decided to throw 404 for preflight request if the route doesn't exists so it behaves same as any other 404 error.
