### ISSUE TITLE
about micrometer

### ISSUE THREAD

**Issue by HelloTo4x** [micronaut-projects/micronaut-micrometer#411]
### Feature description

Hi, i am reading your project, why do you use Micrometer for collecting metric ? why don't you use Grafana + Prometheus to collect log and metric ? Do you know about pros and cons of Micrometer, can you tell me about it

**Comment by alvarosanchez** [comment]
Please post questions in [StackOverflow](https://stackoverflow.com/questions/tagged/micronaut).

You can also try with asking in [Gitter](https://gitter.im/micronautfw/).
