### ISSUE TITLE
netty documentation outdated

### ISSUE THREAD

**Issue by TimothyL96** [micronaut-projects/micronaut-micrometer#437]
### Issue description

In https://github.com/micronaut-projects/micronaut-micrometer/blob/master/src/main/docs/guide/metricsConcepts.adoc

It says  
> The main Control Property for Netty server metrics is micronaut.metrics.binders.netty.enabled, which is false by default.

which is not true, as it is only controlled by 3 subproperties:
netty.bytebuf-allocators.enabled
netty.queues.enabled
netty.channels.enabled

**Comment by sdelamo** [comment]
@yawkat could you check this?
