### ISSUE TITLE
micrometer-cloudwatch feature fails to build as native image

### ISSUE THREAD

**Issue by JamieCressey** [micronaut-projects/micronaut-micrometer#55]
# Problem
The AWS v2 SDK is failing to build into a native image, and is being included (or the CloudWatch subsection is) as part of the micrometer-cloudwatch feature.

```
Error: Classes that should be initialized at run time got initialized during image building:
 io.netty.util.AbstractReferenceCounted the class was requested to be initialized at build time (from the command line). To see why io.netty.util.AbstractReferenceCounted got initialized use -H:+TraceClassInitialization

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
```

# Steps to Reproduce
- `mn create-app test --features aws-api-gateway-graal --features micrometer-cloudwatch`
- `cd test`
- `./docker-build.sh`

```
mn --version
| Micronaut Version: 1.2.8
| JVM Version: 11.0.5
```

**Comment by ilopmar** [comment]
If you create a new application (tested with Micronaut 2.0.1):

```
mn create-app foo --features=micrometer-cloudwatch,graalvm
``` 

And then add `--report-unsupported-elements-at-runtime` to `native-image.properties` it works. The usage of that flag is discouraged so I've opened and issue on graalvm issue tracker: https://github.com/oracle/graal/issues/2736

**Comment by charlie-harvey** [comment]
I bumped into this because I need aws-sdk-v2 explicitly. I am reading from and writhing to a bucket. Thanks for the workaround.

**Comment by alvarosanchez** [comment]
This is working as of Micronaut 2.2
