### ISSUE TITLE
Add support for opentelemetry and Micrometer

### ISSUE THREAD

**Issue by javiertoja** [micronaut-projects/micronaut-micrometer#615]
### Feature description

Currently micrometer offers a bridge that integrates with opentelemtry [link to bridge class](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/micrometer/micrometer-1.5/library/src/main/java/io/opentelemetry/instrumentation/micrometer/v1_5/OpenTelemetryMeterRegistry.java).

I would like to request the creation of a micronaut dependency that provides this class and allows the configuration in combination with the micronaut opentelemtry exporter of a way of exporting metrics using the opentelemetry exporter

**Comment by javiertoja** [comment]
Hello I've found that micrometer is currently providing an exporter https://mvnrepository.com/artifact/io.micrometer/micrometer-registry-otlp, and I would like to give it a try to integrate this into micronaut instead of adding a bridge. I've also detected that micronaut otlp dependencies are not wrapping executor services for context propagation, but this is a different topic

**Comment by sdelamo** [comment]
@n0tl3ss thoughts?
