### ISSUE TITLE
Docs for Micrometer Observation support. 

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-micrometer#618]
### Issue description

We merged this PR [Micrometer Observation Support](https://github.com/micronaut-projects/micronaut-micrometer/pull/585) which does not contain any documentation. We should not add undocumented features.

**Comment by sdelamo** [comment]
@n0tl3ss can you add documentation for this feature?

**Comment by n0tl3ss** [comment]
Hi @sdelamo, I have created PR for docs. I am sorry that I haven't added docs as part of feature PR.
