### ISSUE TITLE
Add support for Prometheus Pushgateway

### ISSUE THREAD

**Issue by PavelZeger** [micronaut-projects/micronaut-micrometer#672]
### Feature description

Spring Boot has out of the box support for Prometheus Pushgateway. We would like to use the same approach with Micronaut as well including metrics for monitoring Prometheus Simple client. Integration with PicoCLI is a convenient way to use Micronaut for fast jobs but lack of metrics support is very inconvenient.

**Comment by graemerocher** [comment]
Fixed in https://github.com/micronaut-projects/micronaut-micrometer/pull/848
