### ISSUE TITLE
Bean seems used even if disabled in Micronaut 4.7.0

### ISSUE THREAD

**Issue by bj-eberhardt** [micronaut-projects/micronaut-micrometer#881]
### Expected Behavior

The build should work and the micronaut integration test should pass and respect disabled beans when used in a Context annotated controller.

### Actual Behaviour

The micronaut tests failed, as the application cannot be started due to a bean been used that is disabled by the `@Requires ` annotation set by a property in the configuration.

### Steps To Reproduce

1. Using Micronaut 4.7.0 with gradle and kapt and micrometer setup
2. Use a Client and a specific filter and add it to an Controller that is annotated with `@Context`
3. Disable web metrics bindings
4. Run gradlew test

You can also have a look at the example in https://github.com/bj-eberhardt/micronaut-4.7-bean-error.
When i change the Controller to be Singleton it works, but with Context annotation it fails.
It seems the ClientMetricsFilter bean is retrieved and used, but in fact due to the Requires annotation, it should be disabled (micronaut.metrics.binders.web.enabled=false).

Please have a look.

### Environment Information

- Java 22 checked different distributions
- MacOs and Windows

### Example Application

https://github.com/bj-eberhardt/micronaut-4.7-bean-error

### Version

4.7.0

**Comment by mrwilby** [comment]
@dstepanov Did this fix make it into the 5.10.x branch ? We can reproduce this same issue now we upgraded to micronaut platform 4.8.0 (we're using Java 21)...


**5.9.x** => https://github.com/micronaut-projects/micronaut-micrometer/blob/b070bebb1b21fe0f81099873b7c8d2c6fe587f54/micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/ClientMetricsFilter.java#L47

**5.10.x** => https://github.com/micronaut-projects/micronaut-micrometer/blob/1ee2d279f85f8402410d30ba42f6afa3bc67f2d0/micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/ClientMetricsFilter.java#L47

Thanks
