### ISSUE TITLE
Add a tag to provide hostname on http.client.requests metrics

### ISSUE THREAD

**Issue by alexanderburley** [micronaut-projects/micronaut-micrometer#9]
For our monitoring purposes we would like to seperate our http.client.requests metrics by the hostname of each request. At the moment we can only get the uri for that http request.

Is this something that you would be open to including or is their another workaround for in including the hostname in the metric tags?

**Comment by graemerocher** [comment]
Seems a reasonable request. PRs welcome!

**Comment by thiagolocatelli** [comment]
@graemerocher is the package io.micronaut.configuration.metrics.binder.web the best place for this change? I can take a look at it and maybe be able to provide with the enhancement. Thank you

**Comment by graemerocher** [comment]
Yes seems to be
